version = 0.1

[default.global.parameters]
debug = false
region = "ap-northeast-1"

[default.validate.parameters]
lint = true

[default.build.parameters]
cached = true
parallel = true
use_container = false
manifest = "./app/package.json"

[default.deploy.parameters]
stack_name = "sam-app-ts-api"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
resolve_s3 = true
s3_prefix = "sam-app-ts-api"
confirm_changeset = false
