AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  IndexFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: index.lambdaHandler
      Role: !GetAtt IndexFunctionRole.Arn
    Method:
      BuildMethod: esbuild
      BuildProperties:
        Minify: True
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app/functions/index.ts

  IndexFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: IndexFunctionRole

